language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker pull postgres
  - docker run --name some-postgres -p 5433:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

jobs:
  include:
    - stage: Tests
      script: gradle test
    - stage: Tests
      script: gradle integrationtest
    - stage: Tests
      script: gradle apitest
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: ibc-acamp-service-staging
        api_key: 2e68b8cf-81e9-4ad0-a325-486a72cd897c
    - stage: test staging
      script: 'curl http://ibc-acamp-service-staging.herokuapp.com'
#    - stage: deploy to production
#      script: skip
#      deploy:
#        <<: *heroku
#        app: sf-stages-production
#    - stage: test production
#      script: 'curl http://sf-stages-production.herokuapp.com'