language: java
jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: Tests
      script: gradle test
#      script: gradle integrationtest
#      script: gradle apitest
#    - stage: unit tests
#      script: "Running unit tests (2)"
#    - stage: deploy to staging
#      script: skip
#      deploy: &heroku
#        provider: heroku
#        app: sf-stages-staging
#        api_key: $HEROKU_AUTH_TOKEN
#    - stage: test staging
#      script: 'curl http://sf-stages-staging.herokuapp.com'
#    - stage: deploy to production
#      script: skip
#      deploy:
#        <<: *heroku
#        app: sf-stages-production
#    - stage: test production
#      script: 'curl http://sf-stages-production.herokuapp.com'